# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v9DtEqJ68IZzrR48ytbClHrzShU064_Y
"""

import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

# Load your dataset (replace with your actual file path if needed)
df = pd.read_csv("fatigue_dataset.csv")

# Select only the physiological features for clustering
features = ["HR (bpm)", "Speed (km/h)", "Breathing (/min)", "Temp (°C)"]
X = df[features]

# Standardize the features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Apply KMeans clustering
kmeans = KMeans(n_clusters=3, random_state=42)
df["Fatigue Cluster"] = kmeans.fit_predict(X_scaled)

# Determine which cluster is which fatigue level based on average HR
cluster_hr_means = df.groupby("Fatigue Cluster")["HR (bpm)"].mean().sort_values()

# Map clusters to fatigue levels (lower HR = more fit)
cluster_color_map = {
    cluster_hr_means.index[0]: "Green",   # Most fit
    cluster_hr_means.index[1]: "Yellow",  # Possibly fatigued
    cluster_hr_means.index[2]: "Red"      # Most fatigued
}

# Assign fatigue level to each player
df["Fatigue Level"] = df["Fatigue Cluster"].map(cluster_color_map)

# Drop the cluster number column if not needed
df.drop(columns=["Fatigue Cluster"], inplace=True)

# Save the updated file (optional)
df.to_csv("fatigue_clustered.csv", index=False)

# Show the results
print(df)